package com.example.sharemoney.service;

import com.example.sharemoney.entity.Category;
import com.example.sharemoney.entity.Expense;
import com.example.sharemoney.entity.ExpenseSplit;
import com.example.sharemoney.entity.Transaction;
import com.example.sharemoney.entity.TransactionType;
import com.example.sharemoney.entity.User;
import com.example.sharemoney.entity.Wallet;
import com.example.sharemoney.event.DebtSettledEvent;
import com.example.sharemoney.event.ExpenseCreatedEvent;
import com.example.sharemoney.exception.AppException;
import com.example.sharemoney.exception.ErrorCode;
import com.example.sharemoney.repository.CategoryRepository;
import com.example.sharemoney.repository.ExpenseRepository;
import com.example.sharemoney.repository.TransactionRepository;
import com.example.sharemoney.repository.UserRepository;
import com.example.sharemoney.repository.WalletRepository;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Slf4j
@Service
@RequiredArgsConstructor
public class PfmEventListener {

    private final WalletRepository walletRepository;
    private final TransactionRepository transactionRepository;
    private final CategoryRepository categoryRepository;
    private final UserRepository userRepository;
    private final ExpenseRepository expenseRepository;
    private final CategoryService categoryService;
    private final AnomalyDetectionService anomalyDetectionService;

    @EventListener
    @Transactional
    public void handleExpenseCreated(ExpenseCreatedEvent event) {
        log.info("PFM Module - Nhận sự kiện tạo chi tiêu nhóm: {}", event.getExpenseId());

        Expense expense =
                expenseRepository
                        .findById(event.getExpenseId())
                        .orElseThrow(() -> new AppException(ErrorCode.EXPENSE_NOT_FOUND));

        // Calculate payer's share
        BigDecimal payerShare = BigDecimal.ZERO;
        for (ExpenseSplit split : expense.getSplits()) {
            if (split.getUser().getId().equals(event.getPayerId())) {
                payerShare = split.getAmountOwed();
                break;
            }
        }

        BigDecimal advancedAmount = event.getAmount().subtract(payerShare);

        // 1. Payer's Main Wallet deductions
        Wallet payerMainWallet = getOrCreateMainWallet(event.getPayerId());

        // Payer's transaction (the full amount they paid)
        if (event.getAmount().compareTo(BigDecimal.ZERO) > 0) {
            Category payerExpenseCategory =
                    categoryService.getOrCreateCategory(
                            event.getPayerId(),
                            event.getCategoryName(),
                            TransactionType.EXPENSE,
                            "📦");
            Transaction tx =
                    Transaction.builder()
                            .wallet(payerMainWallet)
                            .amount(event.getAmount())
                            .type(TransactionType.EXPENSE)
                            .category(payerExpenseCategory)
                            .transactionDate(LocalDateTime.now())
                            .note(event.getTitle())
                            .linkedExpenseId(event.getExpenseId())
                            .isAutoGenerated(true)
                            .build();
            transactionRepository.save(tx);

            // Kích hoạt phát hiện bất thường Z-Score
            anomalyDetectionService.detectAndAlert(tx);
        }

        // Cho phép balance âm cho giao dịch tự động (EDA) — không block flow nhóm
        // khi ví người chi trả chưa đủ tiền
        payerMainWallet.setBalance(payerMainWallet.getBalance().subtract(event.getAmount()));
        walletRepository.save(payerMainWallet);

        // 2. Debtors' Liability Wallet deductions (Bypassed under Cash Basis: debtor only registers
        // expense on debt settlement)
        /*
        for (ExpenseSplit split : expense.getSplits()) {
            if (!split.getUser().getId().equals(event.getPayerId())) {
                UUID debtorId = split.getUser().getId();
                BigDecimal debtorShare = split.getAmountOwed();

                if (debtorShare.compareTo(BigDecimal.ZERO) > 0) {
                    Wallet debtorLiabilityWallet = getOrCreateLiabilityWallet(debtorId);
                    Category debtorExpenseCategory = categoryService.getOrCreateCategory(debtorId,
                            event.getCategoryName(), TransactionType.EXPENSE, "📦");

                    Transaction txDebtor = Transaction.builder()
                            .wallet(debtorLiabilityWallet)
                            .amount(debtorShare)
                            .type(TransactionType.EXPENSE)
                            .category(debtorExpenseCategory)
                            .transactionDate(LocalDateTime.now())
                            .note("Nợ nhóm: " + event.getTitle())
                            .linkedExpenseId(event.getExpenseId())
                            .isAutoGenerated(true)
                            .build();
                    transactionRepository.save(txDebtor);

                    debtorLiabilityWallet.setBalance(debtorLiabilityWallet.getBalance().subtract(debtorShare));
                    walletRepository.save(debtorLiabilityWallet);
                }
            }
        }
        */
    }

    @EventListener
    @Transactional
    public void handleDebtSettled(DebtSettledEvent event) {
        log.info("PFM Module - Nhận sự kiện thanh toán nợ: {}", event.getSettlementExpenseId());

        // 1. Debtor pays money back (Deducted as EXPENSE from debtor's Main Wallet)
        Wallet debtorMainWallet = getOrCreateMainWallet(event.getDebtorId());
        Category debtorExpenseCategory =
                categoryService.getOrCreateCategory(
                        event.getDebtorId(), "Hóa đơn", TransactionType.EXPENSE, "🧾");

        Transaction debtorMainTx =
                Transaction.builder()
                        .wallet(debtorMainWallet)
                        .amount(event.getAmount())
                        .type(TransactionType.EXPENSE)
                        .category(debtorExpenseCategory)
                        .transactionDate(LocalDateTime.now())
                        .note("Thanh toán nợ nhóm")
                        .linkedExpenseId(event.getSettlementExpenseId())
                        .isAutoGenerated(true)
                        .build();

        // Cho phép balance âm cho giao dịch tự động (EDA) — debtor đã trả tiền qua ngân hàng/tiền mặt
        debtorMainWallet.setBalance(debtorMainWallet.getBalance().subtract(event.getAmount()));
        walletRepository.save(debtorMainWallet);
        transactionRepository.save(debtorMainTx);

        // 2. Creditor receives money (Transfer In to Main Wallet)
        Wallet creditorMainWallet = getOrCreateMainWallet(event.getCreditorId());
        Category creditorTransferInCategory =
                categoryService.getOrCreateCategory(
                        event.getCreditorId(), "Nhận tiền nhóm", TransactionType.TRANSFER, "⬅️");

        Transaction creditorTx =
                Transaction.builder()
                        .wallet(creditorMainWallet)
                        .amount(event.getAmount())
                        .type(TransactionType.TRANSFER)
                        .category(creditorTransferInCategory)
                        .transactionDate(LocalDateTime.now())
                        .note("Thu hồi nợ nhóm")
                        .linkedExpenseId(event.getSettlementExpenseId())
                        .isAutoGenerated(true)
                        .build();

        creditorMainWallet.setBalance(creditorMainWallet.getBalance().add(event.getAmount()));
        walletRepository.save(creditorMainWallet);
        transactionRepository.save(creditorTx);
    }

    @EventListener
    @Transactional
    public void handleExpenseDeleted(com.example.sharemoney.event.ExpenseDeletedEvent event) {
        log.info("PFM Module - Xóa khoản chi: {}", event.getExpenseId());
        List<Transaction> txs = transactionRepository.findByLinkedExpenseId(event.getExpenseId());

        for (Transaction tx : txs) {
            if (tx.isAutoGenerated()) {
                Wallet wallet = tx.getWallet();
                if (tx.getType() == TransactionType.INCOME) {
                    wallet.setBalance(wallet.getBalance().subtract(tx.getAmount()));
                } else if (tx.getType() == TransactionType.EXPENSE) {
                    wallet.setBalance(wallet.getBalance().add(tx.getAmount()));
                } else if (tx.getType() == TransactionType.TRANSFER) {
                    // All auto-generated TRANSFER transactions (e.g. from handleDebtSettled) are
                    // TRANSFER IN for the creditor.
                    // Therefore, to rollback, we must subtract the amount from the wallet.
                    wallet.setBalance(wallet.getBalance().subtract(tx.getAmount()));
                }
                walletRepository.save(wallet);
                transactionRepository.delete(tx);
            } else {
                tx.setLinkedExpenseId(null);
                transactionRepository.save(tx);
            }
        }
    }

    @EventListener
    @Transactional
    public void handleExpenseUpdated(com.example.sharemoney.event.ExpenseUpdatedEvent event) {
        log.info("PFM Module - Cập nhật khoản chi: {}", event.getExpenseId());
        // 1. Rollback old transactions
        handleExpenseDeleted(
                new com.example.sharemoney.event.ExpenseDeletedEvent(event.getExpenseId()));

        // 2. Re-create new transactions
        handleExpenseCreated(
                new com.example.sharemoney.event.ExpenseCreatedEvent(
                        event.getExpenseId(),
                        event.getPayerId(),
                        event.getAmount(),
                        event.getTitle(),
                        event.getCategoryName()));
    }

    private Wallet getOrCreateMainWallet(UUID userId) {
        List<Wallet> wallets = walletRepository.findByUser_IdAndIsLiability(userId, false);
        if (!wallets.isEmpty()) return wallets.get(0);

        User user =
                userRepository
                        .findById(userId)
                        .orElseThrow(() -> new AppException(ErrorCode.USER_NOT_FOUND));
        Wallet newWallet =
                Wallet.builder()
                        .user(user)
                        .name("Ví mặc định")
                        .balance(BigDecimal.ZERO)
                        .currency("VND")
                        .isLiability(false)
                        .build();
        return walletRepository.save(newWallet);
    }

    private Wallet getOrCreateLiabilityWallet(UUID userId) {
        List<Wallet> wallets = walletRepository.findByUser_IdAndIsLiability(userId, true);
        if (!wallets.isEmpty()) return wallets.get(0);

        User user =
                userRepository
                        .findById(userId)
                        .orElseThrow(() -> new AppException(ErrorCode.USER_NOT_FOUND));
        Wallet newWallet =
                Wallet.builder()
                        .user(user)
                        .name("Ví trả sau (Nợ nhóm)")
                        .balance(BigDecimal.ZERO)
                        .currency("VND")
                        .isLiability(true)
                        .build();
        return walletRepository.save(newWallet);
    }
}
